package constants

var (
	KeySystem             = []byte("System")
	KeyAccount            = []byte("Account")
	KeyAllExtrinsicsLen   = []byte("AllExtrinsicsLen")
	KeyAura               = []byte("Aura")
	KeyAuthorities        = []byte("Authorities")
	KeyBalances           = []byte("Balances")
	KeyBlockHash          = []byte("BlockHash")
	KeyBlockWeight        = []byte("BlockWeight")
	KeyCurrentSlot        = []byte("CurrentSlot")
	KeyDidUpdate          = []byte("DidUpdate")
	KeyDigest             = []byte("Digest")
	KeyEventCount         = []byte("EventCount")
	KeyEvents             = []byte("Events")
	KeyEventTopics        = []byte("EventTopics")
	KeyExecutionPhase     = []byte("ExecutionPhase")
	KeyExtrinsicCount     = []byte("ExtrinsicCount")
	KeyExtrinsicData      = []byte("ExtrinsicData")
	KeyExtrinsicIndex     = []byte(":extrinsic_index")
	KeyGrandpaAuthorities = []byte(":grandpa_authorities")
	KeyLastRuntimeUpgrade = []byte("LastRuntimeUpgrade")
	KeyNextFeeMultiplier  = []byte("NextFeeMultiplier")
	KeyNow                = []byte("Now")
	KeyNumber             = []byte("Number")
	KeyParentHash         = []byte("ParentHash")
	KeyTimestamp          = []byte("Timestamp")
	KeyTotalIssuance      = []byte("TotalIssuance")
	KeyTransactionPayment = []byte("TransactionPayment")
	TransactionLevelKey   = []byte(":transaction_level:")
)
